version: '{build}'

image: Visual Studio 2015

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - ps: cinst sbt

build_script:
  - sbt compile

test_script:
  - sbt assembly

cache:
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.sbt'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
